version: '3.8'

services:
  server:
    build:
      context: .
    command: sh -c "flask db upgrade && python run.py"
    container_name: app
    restart: on-failure
    image: ramseytrinh338/uetodo-backend:v2
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - FLASK_APP=run.py
      - DATABASE_URL=postgresql://postgres:password@db:5432/uetodo

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: on-failure

  celery:
    build:
      context: .
    command: celery -A celery_worker.celery worker --loglevel=info
    container_name: celery_worker
    restart: on-failure
    depends_on:
      - server
      - rabbitmq

  db:
    image: postgres:16
    container_name: postgresql
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: uetodo
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: