export {default as Home} from "./Home";
export {default as SignUp} from "./SignUp";
export {default as Login} from "./Login";
export {default as Dashboard} from "./MainContent/Dashboard"
export {default as Task} from "./MainContent/Task"
export {default as Calendar} from "./MainContent/Calendar"
export {default as Profile} from "./User/Profile"
export {default as ResetPassword} from "./User/ResetPassword"
export {default as ResetPasswordForm} from "./User/ResetPasswordForm"
export {default as About} from "./About";
export {default as Product} from "./Product";
export {default as Setting} from "./User/Setting";