"""update Task

Revision ID: 0fd6fb62e2ff
Revises: bb49360e08fb
Create Date: 2025-05-28 13:22:56.233141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fd6fb62e2ff'
down_revision = 'bb49360e08fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(),
               type_=sa.Boolean(),
               existing_nullable=False,
               postgresql_using="status::boolean")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    # ### end Alembic commands ###
