"""create_user_and_token_model

Revision ID: 54411b3859a9
Revises: 
Create Date: 2025-05-21 14:07:03.235715

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '54411b3859a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('email', sa.String(length=255), nullable=False),
                    sa.Column('password_hash', sa.String(length=255), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('dob', sa.Date(), nullable=False),
                    sa.Column('gender', sa.String(length=10), nullable=False),
                    sa.Column('phone_number', sa.String(length=15), nullable=False),
                    sa.Column('role', sa.String(length=10), nullable=False),
                    sa.Column('avatar_url', sa.Text(), nullable=False),
                    sa.Column('is_verified', sa.Boolean(), nullable=False),
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    op.create_table('tokens',
                    sa.Column('refresh_token', sa.String(), nullable=True),
                    sa.Column('confirm_token', sa.String(), nullable=True),
                    sa.Column('reset_token', sa.String(), nullable=True),
                    sa.Column('verification_code', sa.String(length=6), nullable=True),
                    sa.Column('reset_code', sa.String(length=6), nullable=True),
                    sa.Column('verification_code_expiration', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('reset_code_expiration', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('user_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tokens')
    op.drop_table('users')
    # ### end Alembic commands ###
