"""update User model

Revision ID: bb49360e08fb
Revises: b9630c5009e3
Create Date: 2025-05-27 23:25:53.525237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb49360e08fb'
down_revision = 'b9630c5009e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=10), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
